; ===== Platform Override for Personal WLED-MM Projects =====
; Variants:
; - S: AudioReactive only (Base Flash)
; - M: AudioReactive + Battery (LiPo)
; - L: AudioReactive + Battery + DMX (Art-Net)

[platformio]
default_envs = blue_S, blue_M, blue_L, purple_S, purple_M, purple_L, black_S, black_M, black_L

; === BlueBoard (ESP32) ===
[env:blue_S]
platform = espressif32@ ~6.3.2
board = esp32dev
framework = arduino
build_flags = -DWLED_AUDIO_REACTIVE
lib_deps =
  https://github.com/pbolduc/AsyncTCP.git@1.2.0
  https://github.com/softhack007/LITTLEFS-threadsafe.git#master
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

[env:blue_M]
platform = espressif32@ ~6.3.2
board = esp32dev
framework = arduino
build_flags =
  -DWLED_AUDIO_REACTIVE
  -DWLED_USE_BATTERY
lib_deps =
  https://github.com/pbolduc/AsyncTCP.git@1.2.0
  https://github.com/softhack007/LITTLEFS-threadsafe.git#master
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

[env:blue_L]
platform = espressif32@ ~6.3.2
board = esp32dev
framework = arduino
build_flags =
  -DWLED_AUDIO_REACTIVE
  -DWLED_USE_BATTERY
  -DWLED_ENABLE_DMX
lib_deps =
  https://github.com/pbolduc/AsyncTCP.git@1.2.0
  https://github.com/softhack007/LITTLEFS-threadsafe.git#master
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

; === PurpleBoard (ESP32-S2 - Lolin S2 Mini) ===
[env:purple_S]
platform = espressif32@ ~6.3.2
board = lolin_s2_mini
framework = arduino
build_flags = -DWLED_AUDIO_REACTIVE
lib_deps =
  https://github.com/pbolduc/AsyncTCP.git@1.2.0
  https://github.com/softhack007/LITTLEFS-threadsafe.git#master
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

[env:purple_M]
platform = espressif32@ ~6.3.2
board = lolin_s2_mini
framework = arduino
build_flags =
  -DWLED_AUDIO_REACTIVE
  -DWLED_USE_BATTERY
lib_deps =
  https://github.com/pbolduc/AsyncTCP.git@1.2.0
  https://github.com/softhack007/LITTLEFS-threadsafe.git#master
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

[env:purple_L]
platform = espressif32@ ~6.3.2
board = lolin_s2_mini
framework = arduino
build_flags =
  -DWLED_AUDIO_REACTIVE
  -DWLED_USE_BATTERY
  -DWLED_ENABLE_DMX
lib_deps =
  https://github.com/pbolduc/AsyncTCP.git@1.2.0
  https://github.com/softhack007/LITTLEFS-threadsafe.git#master
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

; === BlackBoard (ESP32-C3 - esp32-c3-devkitm-1) ===

[env:black_S]
platform = espressif32@ ~6.3.2
board = esp32-c3-devkitm-1
framework = arduino
build_flags = -DWLED_AUDIO_REACTIVE
lib_deps =
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

[env:black_M]
platform = espressif32@ ~6.3.2
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -DWLED_AUDIO_REACTIVE
  -DWLED_USE_BATTERY
lib_deps =
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}

[env:black_L]
platform = espressif32@ ~6.3.2
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -DWLED_AUDIO_REACTIVE
  -DWLED_USE_BATTERY
  -DWLED_ENABLE_DMX
lib_deps =
  makuna/NeoPixelBus@2.7.5
  ${env.lib_deps}
